name: deploy_storybook

on:
  pull_request:
    types: ["opened", "edited", "synchronize"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: npm install and build
        run: |
          npm install
          npm run build-storybook  --quiet
      - name: Deploy to netlify
        id: deploy_with_nelify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=./storybook-static
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      - uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const outputs = [
              "Netlify CLI's outputs... :rocket:",
              "Netlify cli output: ${{ steps.deploy_with_nelify.outputs.NETLIFY_OUTPUT }}",
              "Log: ${{ steps.deploy_with_nelify.outputs.NETLIFY_LOGS_URL }}",
              "Website Draft URL: ${{ steps.deploy_with_nelify.outputs.NETLIFY_URL }}",
              "Live URL: ${{ steps.deploy_with_nelify.outputs.NETLIFY_LIVE_URL }}",
            ]
            const body = outputs.join("\n")

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })

      - name: test echo
        run: |
          echo "${{ steps.deploy_with_nelify.outputs.NETLIFY_OUTPUT }}"
          echo "${{ steps.deploy_with_nelify.outputs.NETLIFY_URL }}"
          echo "${{ steps.deploy_with_nelify.outputs.NETLIFY_LOGS_URL }}"
          echo "${{ steps.deploy_with_nelify.outputs.NETLIFY_LIVE_URL }}"
